---
- name: Verifica se o Docker Swarm está habilitado
  shell: docker info
  changed_when: False
  register: docker_info

- name: Cria o cluster no servidor manager
  shell: docker swarm init --advertise-addr {{ ip_manager }}:2377
  when: "docker_info.stdout.find('Swarm: active') == -1 and 'manager' in inventory_hostname"

- name: Armazena o token de worker
  shell: docker swarm join-token -q worker
  changed_when: False
  register: docker_worker_token
  when: "docker_info.stdout.find('Swarm: active') == -1 and 'manager' in inventory_hostname"

- name: Adiciona swarm worker1 no cluster
  shell: docker swarm join --token "{{ docker_worker_token.stdout }}" {{ ip_manager }}:2377 
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1
   and docker_info.stdout.find('Swarm: pending') == -1
   and 'worker1' in inventory_hostname"

- name: Adiciona swarm worker2 no cluster
  shell: docker swarm join --token "{{ docker_worker_token.stdout }}" {{ ip_manager }}:2377 
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1
   and docker_info.stdout.find('Swarm: pending') == -1
   and 'worker2' in inventory_hostname  

...   