---
- name: Cria o cluster no servidor manager
  shell: docker swarm init --advertise-addr {{ ip_manager }}:2377
  when: "'manager' in inventory_hostname"
  tags: init-swarm

- name: Armazena join token worker
  shell: docker swarm join-token worker | grep docker > /tmp/token-worker.sh
  when: "'manager' in inventory_hostname"
  tags: armazena-token-worker

- name: Pega arquivo token
  fetch:
    src: /tmp/token-worker.sh
    dest: files/token-worker.sh
    flat: yes
  when: "'manager' in inventory_hostname"
  tags: fetch-token-file

- name: Copia arquivo token worker para VMs workers
  copy:
    src: /home/ubuntu/infrastructure-as-code-project/03-Ansible/files/token-worker.sh
    dest: /home/ubuntu/token-worker.sh
    mode: '0777'
  when: "'worker' in inventory_hostname"
  tags: copy-token-file

- name: Adiciona node host ao cluster
  shell: bash /home/ubuntu/token-worker.sh
  when: "'worker' in inventory_hostname"
  tags: add-node-worker

...    
