version: "3"
services:
  web:
    image: site:1.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webserver

  portainer:
    image: portainer/portainer-ce
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - webserver

networks:
  webserver:

volumes:
  portainer_data:
